# Generated by Django 5.2.3 on 2025-06-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Материал')),
                ('slug', models.SlugField(max_length=100)),
                ('type', models.CharField(choices=[('laba', 'Лабораторная работа'), ('independent ', 'Самостоятельная работа'), ('lecture', 'Лекция')], max_length=15, verbose_name='Тип материала')),
                ('content', models.JSONField(verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Предмет')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('variant', models.PositiveSmallIntegerField(verbose_name='Вариант')),
                ('content', models.JSONField(verbose_name='Решение')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Предмет'),
        ),
    ]
