# Generated by Django 5.2.3 on 2025-07-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('subject', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('material', 'slug')},
        ),
    ]
