# Generated by Django 5.2.3 on 2025-08-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attachedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
